# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
---
name: Quality

on:
  workflow_dispatch:
    inputs:
      alertLevel:
        description: 'Vale Minimum Alert level'
        required: true
        default: 'error'
        type: choice
        options:
          - suggestion
          - warning
          - error
  push:
    paths:
      - 'docs/**'
    branches:
      - '1.0'
      - '1.1'
  pull_request:
    paths:
      - 'docs/**'
    branches:
      - '1.0'
      - '1.1'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.8.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.8.0
          cache: 'npm'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor
          sudo snap install vale

      - name: Lint Antora.yml
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: docs/antora.yml
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_filepath: .yamllint.yml
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Vale Linter
        uses: errata-ai/vale-action@v2.1.0
        with:
          files: docs/
          fail_on_error: true
          level: ${{ github.event.inputs.alertLevel }}
